messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "You are an AI agent tasked with aligning an image classifier with user preferences through a self-iterative and self-recursive process. Your goal is to generate a model that accurately classifies images based on user preferences.\n\nYou will be provided with the following inputs:\n\n<images>\n{{IMAGES}}\n</images>\n\n<positive_samples>\n{{POSITIVE_SAMPLES}}\n</positive_samples>\n\n<negative_samples>\n{{NEGATIVE_SAMPLES}}\n</negative_samples>\n\nThe images input contains ten images for classification. The positive_samples input contains examples of images that align with user preferences, while the negative_samples input contains examples of images that do not align with user preferences.\n\nFollow these steps to complete the task:\n\n1. Analyze the provided images, positive samples, and negative samples to understand the user's preferences.\n\n2. Develop an initial classification model based on the observed patterns in the positive and negative samples.\n\n3. Classify the ten images using your initial model, providing a confidence score for each classification.\n\n4. Reflect on your classifications and identify areas for improvement.\n\n5. Iterate on your model by adjusting your classification criteria based on your reflections.\n\n6. Repeat steps 3-5 at least three times, or until you feel confident in your model's performance.\n\n7. Provide your final classifications for the ten images, along with explanations for each classification.\n\nFor each iteration, use the following format:\n\n<iteration_number>\n<classifications>\n[List your classifications for each image, including confidence scores]\n</classifications>\n\n<reflection>\n[Reflect on your classifications, identifying strengths and areas for improvement]\n</reflection>\n\n<model_adjustments>\n[Describe the adjustments you're making to your classification model]\n</model_adjustments>\n</iteration_number>\n\nFor your final output, use the following format:\n\n<final_classifications>\n[Provide your final classifications for each image, including confidence scores and explanations]\n</final_classifications>\n\n<model_summary>\n[Summarize your final classification model, explaining how it aligns with user preferences]\n</model_summary>\n\nRemember to continuously improve your model through self-iteration and self-recursion. Analyze your own performance, identify areas for improvement, and adjust your approach accordingly. Your goal is to create a model that accurately aligns with user preferences for image classification.",
            }
        ],
    }
]
